version: "3.9"

services:
  db:
    image: postgres:15
    container_name: messaging_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
    container_name: messaging_api
    env_file:
      - .env
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
#      http_proxy: ${HTTP_PROXY}
#      https_proxy: ${HTTPS_PROXY}
#      no_proxy: ${NO_PROXY}

    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  redis_PubSub:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"


volumes:
  postgres_data:

